### ISSUE TITLE
panos_panorama_nat_rule_group with translated_packet.destination.dynamic fails with "Error: Missing type for dynamic"

### ISSUE THREAD

**Issue by qubitrenegade** [terraform-providers/terraform-provider-panos#167]
Hello,

In Terraform 0.12 [`dynamic` blocks](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks) are now defined with the special keyword `dynamic`.  This appears to conflict with [translated_packet.destination.dynamic](https://www.terraform.io/docs/providers/panos/r/panorama_nat_rule_group.html#dynamic) as we receive an error:

```
Error: Missing type for dynamic

  on nat.tf line 26, in resource "panos_panorama_nat_rule_group" "foo":
  26:         dynamic {

All dynamic blocks must have 1 labels (type).
```

Here is an example resource receiving this error:

```
resource "panos_panorama_nat_rule_group" "foo" {
  device_group = "Group 1"

  rule {
    name = "ingress"

    original_packet {
      source_zones          = ["Border"]
      destination_zone      = "Border"
      destination_interface = "ethernet1/1"
      source_addresses      = ["192.168.0.0/23"]
      destination_addresses = ["192.168.0.10", "192.168.0.11"]
      service               = "8000"
    }

    translated_packet {
      source {
        dynamic_ip_and_port {
          interface_address {
            interface = "eth0"
          }
        }
      }

      destination {
        dynamic {
          address = "1.1.1.1"
          port    = 8080
        }
      }
    }
  }
}
```

I _think_ changing [this line](https://github.com/terraform-providers/terraform-provider-panos/blob/146058be6240edb56dbc305959d1bd88ab531e3f/panos/resource_nat_rule_group.go#L298) and [this line](https://github.com/terraform-providers/terraform-provider-panos/blob/master/panos/resource_nat_rule_group.go#L529) to `dynamic_ip_and_port` instead of just `dynamic`, which will match the source block, will resolve this issue.

If that's the case I'd be happy to submit a PR.  :)

Or if we're just misusing the resource we'd love to know too!

Thanks!

**Comment by shinmog** [comment]
@qubitrenegade 

Reaching out to HashiCorp about this...  Hold off on a PR until I get in contact with them.

**Comment by shinmog** [comment]
@qubitrenegade 

Ok, talked with someone in HashiCorp.  This is a regression caused by their new recursive `dynamic` block available in Terraform 0.12.  The name will need to be something different for TF 0.12 users, but I can't just change the name outright to something else as it will break TF 0.11 users.  The HashiCorp person suggested adding a new param that TF 0.12 users could use that would do the same thing, while deprecating the old params so TF 0.11 users know to update their plans.  This way, people using TF 0.11 with the old name can continue to do so for a short while, and TF 0.12 would use the new name, so they could actually use this resource.

So, unfortunately the fix is not very straight forward at all.

As for the new naming, if the panos provider needs to change the name, I want the dynamic and static names to be similar the way that they are now.  So this is more in line with what I'd want to change things to:

`translated_packet.destination.dynamic` > `translated_packet.destination.dynamic_translation`
`translated_packet.destination.static` > `translated_packet.destination.static_translation`

**Comment by qubitrenegade** [comment]
So I can confirm this does work as desired in TF 0.12.  Not sure if there are any other implications/repercussions...

**Comment by shinmog** [comment]
Suggestions...  I think that to unblock yourself, you should go ahead and just change `translated_packet.destination.dynamic` to `translated_packet.destination.dynamic_translation`, change `translated_packet.destination.static` to `translated_packet.destination.static_translation`, compile the provider, and roll with that.

As for fixing this, I need to do some experimentation to see what is and isn't possible, so I can't give any specific feedback on that just quite yet..

**Comment by shinmog** [comment]
@qubitrenegade 

Ok, the fix I've implemented will not break existing plans for Terraform 0.11 users, and will unblock / allow Terraform 0.12 users to actually use these resources.  The fix is the best of a bad situation that HashiCorp put me in, but as long as users stick with one way or the other the resource will behave nicely, and will allow users to have a plan deployed, change the plan to the new style, refresh, and it should work...

From my playing around, it should work, but I'll know for sure soon enough I suppose.  Thanks for finding this and the assist.

I did end up naming the new params `static_translation` and `dynamic_translation` as they made the most sense, and felt natural enough to change if as a user I was told to change variable names.
