### ISSUE TITLE
Feature Request - Redist Profiles

### ISSUE THREAD

**Issue by AnujSehgall** [terraform-providers/terraform-provider-panos#92]
Is there any way to add a redistribution profile to a virtual router?

**Comment by erikpaasonen** [comment]
@AnujSehgall not yet. We're waiting for the same feature in the `panos_panorama_virtual_router` resource. Specifically, we'd be consuming the redist profile in BGP (VPNs to AWS VPCs). Would you use redist profiles with BGP or a different protocol?

The reason I suggest you clarify is because Palo Alto Networks has told us it's a huge job to implement all of the virtual router functionality. They'd like the components (such as which routing protocols) that would actually get used to bubble up to the top in priority.

**Comment by AnujSehgall** [comment]
Hello @erikpaasonen 

I was supposed to use the redist profiles with BGP itself.

**Comment by shinmog** [comment]
Redist profiles will come alongside BGP support.
