### ISSUE TITLE
Terraform crashes with panos_panorama_address_group 

### ISSUE THREAD

**Issue by chewdevs** [terraform-providers/terraform-provider-panos#98]
I'm using the `panos_panorama_address_group` to create address group but terraform is crashing with a simple configuration.

```
Terraform v0.11.10
+ provider.panos v1.4.1
```
Panos version: 8.0.12

Terraform configuration:
```
resource "panos_address_object" "n_lan_projet520" {
    name = "n_lan_projet520"
    value = "10.36.220.0/22"
}

resource "panos_address_object" "cloud-dns-z01n-prd" {
    name = "cloud-dns-z01n-prd"
    value = "10.27.53.3"
}

resource "panos_address_object" "cloud-dns-z02n-prd" {
    name = "cloud-dns-z02n-prd"
    value = "10.94.53.3"
}

resource "panos_panorama_address_group" "dns_clouds_vdr" {
    name = "dns-clouds-vdr"
    static_addresses = ["cloud-dns-z01n-prd", "cloud-dns-z02n-prd"]
}
```

Crash log:
[crash.log](https://github.com/terraform-providers/terraform-provider-panos/files/2579942/crash.log)

**Comment by shinmog** [comment]
@chewdevs 

I see two issues with the above:

1. You're inadvertently trying to use a Panorama resource with a PAN-OS firewall.  You should be using `panos_address_group`, not `panos_panorama_address_group`.
2. You should be using dependencies so that Terraform knows that it needs to create the address objects before it can create the address group.  I'd recommend doing resource attribute variables over `depends_on`, so your address group config would look like this:
```hcl
resource "panos_address_group" "dns_clouds_vdr" {
    name = "dns-clouds-vdr"
    static_addresses = ["${panos_address_object.cloud-dns-z01n-prd.name}", "${panos_address_object.cloud-dns-z02n-prd.name}"]
}
```

Hope this helps!
